language: node_js
node_js: "4"

group: bluezone

addons:
  firefox: "45.1.1esr"

before_install:
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@~3.8.0; npm cache clean; fi
  - tar -xjf /tmp/firefox-45.1.1esr.tar.bz2 --directory /tmp
  - export PATH="/tmp/firefox:$PATH"
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - npm install || (cat npm-debug.log; false)

script:
  - npm run build
  - npm test -- -b PhantomJS -b Chrome -b Firefox
  - npm run lint

deploy:
  provider: script
  script: sh travis.ci/deploy.sh
  on:
    all_branches: true
