language: node_js
cache:
  directories:
  - node_modules
node_js:
  - "6"
group: bluezone
dist: trusty

addons:
  apt:
    packages:
      - google-chrome-stable
  firefox: "latest-esr"
before_install:
  - echo "@console:registry=http://dev-console-npm.stage1.ng.bluemix.net/" >> ~/.npmrc
  - echo "//dev-console-npm.stage1.ng.bluemix.net/:_authToken=\${NPM_TOKEN}" >> ~/.npmrc
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@~3.8.0; npm cache clean; fi
  - if [[ -n "${NPM_TOKEN_WHITEWATER}" ]]; then echo "@ibma:registry=https://npm-registry.whitewater.ibm.com/" >> .npmrc; fi
  - if [[ -n "${NPM_TOKEN_WHITEWATER}" ]]; then echo "//npm-registry.whitewater.ibm.com/:_authToken=${NPM_TOKEN_WHITEWATER}" >> .npmrc; fi
  - tar -xjf /tmp/firefox-latest-esr.tar.bz2 --directory /tmp
  - export PATH="/tmp/firefox:$PATH"
  - export CHROME_BIN=google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - npm prune
  - npm install || (cat npm-debug.log; false)
  - if [[ -n "${NPM_TOKEN_WHITEWATER}" ]]; then npm i @ibma/karma-ibma; fi

script:
  - npm run build
  - npm run test:unit -- -b PhantomJS -b Chrome -b Firefox
  - find tests/spec -name "*.js" ! -name left-nav_spec.js -print0 | xargs -0 -n 1 -P 1 npm run test:unit -- -d -f
  - if [[ -n "${NPM_TOKEN_WHITEWATER}" ]]; then (npm run test:a11y || true); fi
  - npm run lint
deploy:
  provider: script
  script: sh travis.ci/deploy.sh
  on:
    all_branches: true
